name: Auto Merge on Push

on:
  push:
    branches:
      - feature-branch

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Run Super Linter
        uses: github/super-linter@v4
        
      - name: Checkout code
        uses: actions/checkout@v2
        
        env:
          RUN_LOCAL: true
          DEFAULT_BRANCH: dev
